name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Thank you for reporting a issue to this repository. That means alot to me. My lazy developer will be here in a minute to review your first issue ;)"
        pr-message: "Woah :O.. Thank you for your effort for creating a pull request that fixes/implements something thats useful for me. My lazy dev will be here in a minute."
